version: '3.3'

services:
   codenjoy_client_runner:
     image: apofig/codenjoy-client-runner:${CODENJOY_VERSION}
     container_name: codenjoy-client-runner
     command: --spring.profiles.active=${SPRING_PROFILES} --SERVICE_CONTEXT=/${CLIENT_RUNNER_CONTEXT} # --debug
     build:
       context: ./applications
       dockerfile: Dockerfile-client-runner
       args:
         WAR_FILE: ./codenjoy-client-runner.war
         MAINTAINER_NAME: ${MAINTAINER_NAME}
         MAINTAINER_EMAIL: ${MAINTAINER_EMAIL}
     volumes:
       - ./materials/client-runner/sources:/app/${CLIENT_RUNNER_SOLUTION_FOLDER_PATH}
       - ./logs/client-runner:/app/logs
       - /var/run/docker.sock:/var/run/docker.sock:rw
       - /etc/localtime:/etc/localtime:ro
#     ports:                                              #P#
#       - "${CLIENT_RUNNER_PORT}:8080"                    #P#
     restart: always
     environment:
         LOG_DEBUG: "false"
         SERVICE_SOLUTION_FOLDER_PATH: ${CLIENT_RUNNER_SOLUTION_FOLDER_PATH}
         SERVICE_SOLUTION_FOLDER_PATTERN: ${CLIENT_RUNNER_SOLUTION_FOLDER_PATTERN}
         SERVICE_CODENJOY_URL_REGEX: ${CLIENT_RUNNER_CODENJOY_URL_REGEX}

     networks:
         codenjoy:
             ipv4_address: 172.28.1.9

   nginx:
     depends_on:
       - codenjoy_client_runner
     volumes:
       - ./config/nginx/conf.d/client-runner/locations.conf:/etc/nginx/conf.d/client-runner/locations.conf
       - ./config/nginx/conf.d/client-runner/upstreams.conf:/etc/nginx/conf.d/client-runner/upstreams.conf

