FROM java-workspace

ARG WAR_FILE=codenjoy-balancer.war
ARG SPRING_PROFILES=sqlite
ARG CODENJOY_CONTEXT=codenjoy-balancer

ARG MAINTAINER_NAME=User
ARG MAINTAINER_EMAIL=user@email.com
LABEL maintainer="${MAINTAINER_NAME}"

RUN mkdir -p /app

COPY ${WAR_FILE} /app/server.war

WORKDIR /app

ENTRYPOINT ["java","-jar","server.war"]
CMD ["--spring.profiles.active=${SPRING_PROFILES}","--context=/${CODENJOY_CONTEXT}"]
